#!/bin/bash

#ch27

#read-integer: Evaluate the valud of an integer.

echo -n "Please enter an integer -> "
read int


if [[ "$int" =~ ^-?[0-9]+$ ]]; then
	if [ "$int" -eq 0 ]; then
		echo "$int =  zero."
	else
		if [ "$int" -lt 0 ]; then
			echo "$int =  negative"
		else
			echo "$int =  positive"
		fi
		if [ $((int % 2)) -eq 0 ]; then
			echo "$int =  even."
		else 
			echo "$int = odd."
		fi
	fi

else
	echo "int is not an integer." >&2
	exit 1
fi

